<a href="https://colab.research.google.com/github/DFTFT-os/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 6강 - 데이터 전처리 1

데이터전처리 어렵고 규모가 커서 2번에 나눠서 해볼게요오옹

ㅇ 데이터 전처리의 필요성
- GIGO; Garbage In, Garbage Out
- 잘못되거나 부정확한 데이터 입력하면 어떤 정교한 분석 기법을 적용하더라도 잘못된 결과가 출력된다
- 데이터 품질 향상을 통해 분석 결과의 질을 향상시키기 위한 방안이 요구
- 데이터 규모 증가, 신기술 대중화로 다양하고 새로운 유형의 데이터 수집, 여러 이질적인 소스로부터 데이터 수집

ㅇ 전처리 대상 데이터
- 데이터 수집되지 않음: 결측치, 누락된 값
- 일관성이 없는 데이터: mouse, 마우스
- 발생할 수 없는 값(부정확한 값): 판매 수량인데 -10

ㅇ 데이터 전처리의 정의
- 데이터 분석에 앞서 원시 데이터 raw data 를 정제하고 변환하여 분석에 적합한 형태로 만드는 일련의 작업
1. 측정 (구조 이해, 필요 여부 판단)
2. 정제 (정합석 확보, 오류 수정)
3. 통합 (데이터셋 결합)
4. 축소 (크기 축소, 샘플링, 특징 추출)
5. 변환 (형태 변환, 정규화, 요약)
> 5단계 순환, 지속/반복적 수행

ㅇ 어려운 이유
- 방대한 양, 수치형 데이터 뿐만 아니라 텍스트, 이미지, 동영상, 로그 파일 등 다양한 형식이 존재
- 주관적 판단의 개입 여지, 정해진 정답 없고 상황에 따라 적절한 결정
- 다양한 처리 방법, 처리 방법 고정 X, 다양한 접근법 존재
- 시간과 노력 소모, 여러 단계를 반복적으로 확인하고 검토하는 과정

### 6-1 데이터 훑어보기

데이터 불러와서 얘가 어떤 형태 가지고 있나 양은 얼마나 있나 분포는 어떤가,, 훑어보기

In [6]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

# 데이터 측정
df.describe()
# 수치형만 나옴, score에 np.nan 결측치 있어서 count하면 얘는 개수 4개 나옴 age는 5개 ㅇㅇ

# 모든 데이터 타입 측정
df.describe(include='all')
#수치형 말고 나머지도 다 주세용

# 수치형 데이터 측정
df.describe(include=[np.number])

# 범주형 데이터 측정
df.describe(include=['object'])

# 특정 열 분석
df['score'].describe()

count     4.000000
mean     87.500000
std       6.454972
min      80.000000
25%      83.750000
50%      87.500000
75%      91.250000
max      95.000000
Name: score, dtype: float64

### 6-2 DataFrame 열 선택 및 **조작**

In [15]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

# 특정 열 선택
selected_col = df[['이름', '학과', '학점']]
selected_col

# DataFrame 열순서 변경
recorded_cols = df[['학과', '이름', '학년', '학점', '동아리']]
recorded_cols

# DataFrame 열이름 변경 (다른 알고리즘에서 쓸 때 열이름 바꿔야 할 때도 있음)
df_renamed = df.rename(columns={'이름': '학생명', '학점': 'y', '동아리': '과외활동'})
df_renamed

   학생명  학년    y     학과   과외활동
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

### 6-3 DataFrame 행 선택

In [22]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정 (우리가 다룰 데이터의 중요한 속성을 인덱스로 설정해서 탐색 편하게 하고 직관적으로 이해할 수 있게 함)
df = pd.DataFrame(data)
df = df.set_index('이름')
df

#DataFrame 행 선택 loc location
df.loc['김철수']
df.loc[['김철수', '이영희']] #리스트로 만들어서 전달해야 여러개 행 가지고 올 수 있다
df.loc['김철수':'박민수'] #슬라이싱 사용

#DataFrame 위치 기반 행 선택 (몇번째!!행!!가져와죠!!) iloc index location
df.iloc[1] #파이썬이니까 두번째 값 가지고 오고 싶으면 인덱스 1
df.iloc[[2,3]]
df.iloc[1:3]

#DataFrame 조건 기반 선택

     학년   학점    학과   동아리
이름
이영희   2  3.8   경영학  독서토론
박민수   3  4.5  전자공학  로봇공학

### 6-4 DataFrame 정렬

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정

#DataFrame 단일 열 오름차순, 내림차순 정렬

#DataFrame 복수 열 오름차순, 내림차순 정렬

#DataFrame 인덱스 기분 오른차순, 내림차순 정렬

## 6-5 실습 시나리오 - Kaggle을 활용한 데이터 수집 및 측정

- Kaggle([https://www.kaggle.com](https://www.kaggle.com)) 회원 가입
- Kaggle 접근 토큰 생성(API 키)

### Kaggle API 키 업로드

In [ ]:
from google.colab import files
files.upload()

### Kaggle API 키 사용을 위한 Colab 환경 설정

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

### Kaggle 데이터셋 다운로드

In [ ]:
!kaggle competitions download –c store-sales-time-series-forecasting

!unzip store-sales-time-series-forecasting.zip

### Kaggle 데이터셋 DataFrame 로드 및 살펴보기

In [ ]:
import pandas as pd

# Grocery Sales 데이터 DataFrame 로드

# 판매 데이터 살펴보기

### Kaggle 데이터셋 측정

In [ ]:
# 판매 데이터 기본 통계량

# 매장 데이터 기본 정보

# 원유 가격 데이터 기본 정보